services:
  ai-image-online:
    image: ghcr.io/ironmancantfix/ai-image-online:main
    container_name: ai-image-online
    ports:
      - "19090:8080"
    volumes:
      - "/var/apps/ai-image-online/data:/app/data"
    environment:
      - TZ=Asia/Shanghai
      - PORT=8080
    restart: unless-stopped
